#!/bin/bash
set -ex

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_project="${_scripts}/.."
_infra="${_scripts}/../infra"
APP_NAME="smashdown"

# Terraform state, bucket name
AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r '.Account')
terraform_state_bucket="terraform-remote-$AWS_ACCOUNT_ID"

set -a
source "$_project/.env"
set +a

if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  echo "Error: CLOUDFLARE_API_TOKEN is not set" >&2
  exit 1
fi

export TF_VAR_cloudflare_api_token="$CLOUDFLARE_API_TOKEN"

pushd "${_infra}"

terraform init \
  -backend-config bucket="${terraform_state_bucket}" \
  -backend-config="region=${TF_VAR_region:-us-west-2}" \
  -backend-config="key=$APP_NAME" \
  -backend-config="encrypt=true"

terraform apply -auto-approve
popd

