#!/usr/bin/env bash

_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${_dir}/common"

# npm run build

aws s3 sync dist s3://${SITE_DOMAIN}
aws s3 cp dist/index.html s3://${SITE_DOMAIN}/index.html --cache-control max-age=0
# popd